# Prometheus scrape configuration snippet for the Nova metrics exporter.
# Merge into your existing prometheus.yml under the global scrape_configs array.

scrape_configs:
  - job_name: nova-metrics
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: nova
      - source_labels: [__address__]
        target_label: instance
    static_configs:
      - targets:
          - nova-host-01.internal:9640
          - nova-host-02.internal:9640
        labels:
          environment: production
          region: us-central

  # Optional: scrape the docs portal uptime probe exported via blackbox exporter
  - job_name: nova-docs-uptime
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['https://docs.nova.dev']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
